### ISSUE TITLE
Application running on Docker container Tomcat, errors out while fetching AWS Secrets

### ISSUE THREAD

**Issue by nsextus** [awspring/spring-cloud-aws#633]
I have a spring boot v2.7.7 application trying to retrieve secrets from the AWS secrets manager using the below dependency:

> implementation 'io.awspring.cloud:spring-cloud-starter-aws-secrets-manager-config:2.4.2'

The entries in my **application.properties** are as below:

> aws.secretsmanager.region=eu-west-1
aws.secretsmanager.name=my-secrets
spring.config.import=optional:aws-secretsmanager:${aws.secretsmanager.name}

My application is able to retrieve the secrets when it runs on my local system (Windows 10, jdk1.8.0_351, Eclipse/VSCode, Spring boot bundled tomcat), but fails with the below exception when it runs on docker container (Amazon Linux, java-1.8.0-openjdk-headless, Tomcat 8.5) on Amazon Linux.

> INFO  -  -  - c.v.ServletInitializer - The following 8 profiles are active: "default", "local", "abc", "no", "test2", "test1", "bu", "cs"
INFO  -  -  - i.a.c.s.AwsSecretsManagerPropertySources - Loading secrets from AWS Secret Manager secret with name: my-secrets, optional: true
WARN  -  -  - i.a.c.s.AwsSecretsManagerPropertySources - Unable to load AWS secret from my-secrets. The security token included in the request is invalid. (Service: AWSSecretsManager; Status Code: 400; Error Code: UnrecognizedClientException; Request ID: 0d9055a3-36fb-4ffb-af44-f79b57e8e750; Proxy: null)
WARN  -  -  - o.s.b.c.c.ConfigDataEnvironment - Property 'spring.profiles' is invalid and should be replaced with 'spring.config.activate.on-profile' [origin: System Environment Property "SPRING_PROFILES"]
INFO  -  -  - o.s.c.c.s.GenericScope - BeanFactory id=0e9e34da-0415-3daf-b6ff-9462fd1271bb

Previously, my application used "**implementation 'software.amazon.awssdk:secretsmanager:2.18.16'**" dependency to retrieve secrets, and it worked fine on the same docker container. I am even able to retrieve the secret info using AWS CLI from my Amazon Linux system which runs docker ("aws secretsmanager get-secret-value --secret-id my-secrets"). Which means my AWS credentials are valid and correct.

So, my application running on the same docker container fetched the secrets successfully using AWS SDK, but isn't able to using the above mentioned io.awspring dependency. 
And, using the same io.awspring dependency, my application is able to fetch secrets when run on my local system, but fails when run on my docker container.

Could you help me debug and fix this problem please ?

Please revert if you need more information.

**Comment by snigdhasjg** [comment]
`io.awspring.cloud:spring-cloud-starter-aws-secrets-manager-config:2.4.2` uses `com.amazonaws:aws-java-sdk-secretsmanager:1.x.x` version which is `V1` of AWS SDK.

When you run your apps on your local Windows machine, it is using Access key and Secret key (also Session token if configured). 
But when it is running on docker inside Amazon linux on a ec2, it uses instance profile.

I'll suggest you to check which Credential provider you are using. Try to use chain for both credential and region.
Try enabling chain with this:
```yml
cloud:
  aws:
    credentials:
      use-default-aws-credentials-chain: true
    region:
      use-default-aws-region-chain: true
```

**Comment by nsextus** [comment]
Thanks for responding @snigdhasjg !
I have tried adding the config as below, but am still getting the same error when application runs on docker container.
> cloud.aws.credentials.use-default-aws-credentials-chain=true
cloud.aws.region.use-default-aws-region-chain=true

However, it works for me with v3.0.0-M1 & v3.0.0-M2 versions of the API with the below configuration:
**application.properties**
```
spring.cloud.aws.secretsmanager.region=eu-west-1
aws.secretsmanager.name=my-secrets
spring.config.import=aws-secretsmanager:${aws.secretsmanager.name}
```
**build.gradle**
```
implementation 'io.awspring.cloud:spring-cloud-aws-dependencies:3.0.0-M2'
implementation 'io.awspring.cloud:spring-cloud-aws-starter-secrets-manager:3.0.0-M2'
```
But, we would not prefer to go ahead with a milestone version of the API in our production environment. Hence, I'm looking to get it working with v2.4.2 or maybe come back to spring cloud when there's a stable/release version.

Please let me know if there's a fix/workaround with v2.4.2

Thank you!!

**Comment by maciejwalkowiak** [comment]
@nsextus we have just released 3.0 RC1. The GA is coming in 2-4 weeks. Unfortunately I have no time to help with 2.x but I would recommend to dig into differences in how the default credentials provider work between AWS SDK v1 and v2.

**Comment by nsextus** [comment]
Thanks @maciejwalkowiak ! I've tried with 3.0.0-RC1 and am getting the errors which I got with v3.0.0-M3 i.e. incompatible with Java 8. However, v3.0.0-M1 & v3.0.0-M2 had worked for me.

Coming to v2.4.2 implementation, I've tried setting up default credentials provider as below, but the error (The security token included in the request is invalid) still persists
```
package com.example;

import org.springframework.boot.BootstrapRegistry;
import org.springframework.boot.BootstrapRegistryInitializer;

import com.amazonaws.auth.AWSCredentialsProvider;
import com.amazonaws.auth.DefaultAWSCredentialsProviderChain;
import com.amazonaws.regions.Regions;
import com.amazonaws.services.secretsmanager.AWSSecretsManager;
import com.amazonaws.services.secretsmanager.AWSSecretsManagerClient;

public class SecretsManagerBootstrapConfig implements BootstrapRegistryInitializer {

	@Override
	public void initialize(BootstrapRegistry registry) {
		registry.register(AWSSecretsManager.class, context -> {
			
			AWSCredentialsProvider awsCredentialsProvider = new DefaultAWSCredentialsProviderChain();
			return AWSSecretsManagerClient.builder().withCredentials(awsCredentialsProvider).withRegion(Regions.EU_WEST_1).build();
		});
	}
}
```
**src/main/resources/META-INF/spring.factories**
```
org.springframework.boot.BootstrapRegistryInitializer=com.example.SecretsManagerBootstrapConfig
```
I've also tried the below implementation, as a similar one for S3 works for my application (using AWS SDK); but it didn't work for me for secretsmanager with spring cloud:
```
	@Override
	public void initialize(BootstrapRegistry registry) {
		registry.register(AWSSecretsManager.class, context -> {
			
			AWSCredentialsProvider awsCredentialsProvider = new DefaultAWSCredentialsProviderChain();

			final ClientConfiguration clientConfiguration = new ClientConfiguration();
	        clientConfiguration.setProtocol(Protocol.HTTPS);
			AWSSecretsManagerClientBuilder builder = AWSSecretsManagerClientBuilder.standard();
			
			return builder.withClientConfiguration(clientConfiguration)
			.withCredentials(awsCredentialsProvider).withRegion(Regions.EU_WEST_1).build();
		});
	}
```

Please let me know if I am missing anything here..

Thank you!!

**Comment by maciejwalkowiak** [comment]
Ok I'll try - how the credentials should be retrieved? Are they in environment variables? Profile file? Something else? There are multiple ways to obtain credentials and `DefaultAWSCredentialsProviderChain` uses some of them. Perhaps not the right method for your environment.

**Comment by nsextus** [comment]
`InstanceProfileCredentialsProvider` worked for me (secretsmanager), for the application running on the docker container.
So, `DefaultAWSCredentialsProviderChain` worked for S3 but not for secretsmanager.

May I please ask if you have any plans to release AWS spring cloud API (based on AWS SDK V2) which would be compatible with Java 8 ? as the one released yesterday (3.0.0-RC1) seems to be only compatible on Java 17 and Spring boot 3.0

**Comment by maciejwalkowiak** [comment]
There are no plans like this, it would be way too much work.

**Comment by nsextus** [comment]
Thank you!!

So that means, AWS Spring cloud v3.0.0 uses AWS SDK v2 and is only meant for spring boot 3.0 and Java 17;
and applications running spring boot 2.x and Java 8 would have to use spring cloud 2.x which uses AWS SDK v1 ?

**Comment by nsextus** [comment]
I would not prefer to set the `InstanceProfileCredentialsProvider` inside a `BootstrapRegistryInitializer` as it makes configuring different credential providers for different environment difficult.
Instead, I was trying to set 
```
cloud.aws.credentials.instance-profile=true
```
to the environment specific application.properties and expecting spring cloud secretsmanager v2.4.x to configure `InstanceProfileCredentialsProvider`, but it fails with the error "AWSSecretsManagerException: The security token included in the request is invalid"
May I please ask, if I am missing something here ?

Thanks!!

**Comment by maciejwalkowiak** [comment]
@nsextus apologies for late reply.

> So that means, AWS Spring cloud v3.0.0 uses AWS SDK v2 and is only meant for spring boot 3.0 and Java 17;
and applications running spring boot 2.x and Java 8 would have to use spring cloud 2.x which uses AWS SDK v1 ?

Yes exactly.

Secrets Manager and Parameter Store integration are used in the bootstrap phase and there's no way to configure them as easily as other integrations.

Please find an example on how to configure Secrets Manager in 2.4 here: https://github.com/awspring/spring-cloud-aws/issues/205#issuecomment-1030964159

Considering you found out how to get your integrations working, i am closing this issue. Feel free to drop a comment if i missed anything and we can consider reopening.
